# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "BAKS theme"
license = "MIT"
licenselink = "https://github.com/crnkjck/gohugo-theme-baks/blob/master/LICENSE.md"
description = "A theme based on the Ananke Gohugo Theme"
homepage = "https://github.com/theNewDynamic/gohugo-theme-ananke"
tags = ["website", "starter", "responsive", "Disqus", "blog", "Tachyons", "Multilingual", "Stackbit"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = "0.55.0"

[author]
  name = "theNewDynamic"
  homepage = "https://www.thenewdynamic.com/"
